name: Build kernel
on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    env:
      BUILD_SRC: ${{ github.workspace }}/build/
      KERNEL_SRC: ${{ github.workspace }}/kernel/
      CCACHE_DIR: /tmp/ccache/
    defaults:
      run:
        working-directory: ${{ env.BUILD_SRC }}
    steps:
      # Setup build scripts
      - name: Checkout build scripts
        uses: actions/checkout@v4
        with:
          path: ${{ env.BUILD_SRC }}
      - name: Create toolchain hashing key
        run: |
          . "builder.cfg"
          echo "TOOLCHAIN_KEY=$LLVM_VER" >> $GITHUB_ENV
      # Install dependencies
      - run: sudo apt install -y build-essential bison flex ccache
      # Restore or setup toolchain
      - name: Restore toolchain
        id: restore-toolchain
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.BUILD_SRC }}/toolchain
          key: toolchain-${{ env.TOOLCHAIN_KEY }}
      - name: Setup toolchain
        if: steps.restore-toolchain.outputs.cache-hit != 'true'
        id: setup-toolchain
        run: ./setup-toolchain.sh
      - name: Save toolchain
        if: steps.setup-toolchain.outcome == 'success'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.BUILD_SRC }}/toolchain
          key: toolchain-${{ env.TOOLCHAIN_KEY }}
      # Restore build cache
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ github.run_id }}
          restore-keys: |
            ccache-
      - run: ccache --zero-stats
      # Fetch kernel sources and build them
      - name: Checkout kernel sources
        uses: actions/checkout@v4
        with:
          path: ${{ env.KERNEL_SRC }}
          repository: torvalds/linux
          ref: v6.1
      - name: Patch kernel
        run: |
          cd ${{ env.KERNEL_SRC }}
          curl -Lf https://www.kernel.org/pub/linux/kernel/v6.x/patch-6.1.148.xz | unxz | git apply -
          git apply $BUILD_SRC/patches/*.patch
      - name: Build kernel
        run: WRAPPER=ccache ./build.sh sun50iw9_defconfig $KERNEL_SRC -j$(nproc)
      # Post-build stuff
      - uses: actions/upload-artifact@v4
        with:
          name: kernel-sun50iw9-mainline
          path: ${{ env.BUILD_SRC }}/out/*
      - name: Clean up ccache
        run: |
          ccache -M 200MiB
          ccache --cleanup
          ccache -s >> $GITHUB_STEP_SUMMARY
