name: Build Android kernel
on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    env:
      BUILD_SRC: ${{ github.workspace }}/build/
      KERNEL_SRC: ${{ github.workspace }}/kernel/
      CCACHE_DIR: /tmp/ccache/
    defaults:
      run:
        working-directory: ${{ env.BUILD_SRC }}
    steps:
      # Setup build scripts
      - name: Checkout build scripts
        uses: actions/checkout@v4
        with:
          path: ${{ env.BUILD_SRC }}
      - name: Create toolchain hashing key
        run: |
          . "builder.cfg"
          echo "TOOLCHAIN_KEY=$LLVM_VER" >> $GITHUB_ENV
      # Install dependencies
      - run: sudo apt install -y build-essential bison flex ccache
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: ${{ env.BUILD_SRC }}/requirements.txt
      - run: pip install -r ${{ env.BUILD_SRC }}/requirements.txt
      # Restore or setup toolchain
      - name: Restore toolchain
        id: restore-toolchain
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.BUILD_SRC }}/toolchain
          key: toolchain-${{ env.TOOLCHAIN_KEY }}
      - name: Setup toolchain
        if: steps.restore-toolchain.outputs.cache-hit != 'true'
        id: setup-toolchain
        run: ./setup-toolchain.sh
      - name: Save toolchain
        if: steps.setup-toolchain.outcome == 'success'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.BUILD_SRC }}/toolchain
          key: toolchain-${{ env.TOOLCHAIN_KEY }}
      # Restore build cache
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ github.run_id }}
          restore-keys: |
            ccache-
      # Fetch kernel sources and build them
      - name: Checkout kernel sources
        uses: actions/checkout@v4
        with:
          path: ${{ env.KERNEL_SRC }}
          repository: zatrit/android_kernel_sdm845_mainline
      - name: Build kernel
        run: ./build.sh sdm845_defconfig ${{ env.KERNEL_SRC }} --wrapper ccache --quiet --fail-fast
      - uses: actions/upload-artifact@v4
        with:
          name: kernel-sdm845-mainline
          path: ${{ env.BUILD_SRC }}/out/*
